[features]
seeds = false
[programs.devnet]
myepicproject = "EgAEYRZD8pYTu5utF5fzXcLjeFFkN62LwL49oMMAvyTV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/fujiidaiki/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
